### ISSUE TITLE
[ERROR] Exception in command `project`: Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body In content: Must be 2000 or fewer in length.

### ISSUE THREAD

**Issue by cwarwicker** [cwarwicker/discord-Writer-Bot#10]
`[ERROR] ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 83, in wrapped\n    ret = await coro(*args, **kwargs)\n', '  File "/var/www/discord-Writer-Bot/cogs/writing/project.py", line 61, in project\n    return await self.run_view(context)\n', '  File "/var/www/discord-Writer-Bot/cogs/writing/project.py", line 142, in run_view\n    return await context.send(user.get_mention() + \', \' + lib.get_string(\'project:list\', user.get_guild()) + message)\n', '  File "/usr/local/lib/python3.8/dist-packages/discord/abc.py", line 856, in send\n    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)\n', '  File "/usr/local/lib/python3.8/dist-packages/discord/http.py", line 225, in request\n    raise HTTPException(r, data)\n', 'discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body\nIn content: Must be 2000 or fewer in length.\n', '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/bot.py", line 892, in invoke\n    await ctx.command.invoke(ctx)\n', '  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 797, in invoke\n    await injected(*ctx.args, **ctx.kwargs)\n', '  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 92, in wrapped\n    raise CommandInvokeError(exc) from exc\n', 'discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body\nIn content: Must be 2000 or fewer in length.\n']
`

**Comment by cwarwicker** [comment]
Might need to split the message into multiple messages if it's more than 2000 characters. Not sure of another way to do this.
