### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by cwarwicker** [cwarwicker/discord-Writer-Bot#96]
Making this as a general issue for the on-going performance issues, which started at the start of Nano (Nov 1st).

Currently getting a lot of errors when users try to run commands, plus the bot either taking a long time to respond, or it doesn't respond at all.

The errors can occur from any command, and always seem to originate from the attempt to send a message.

Examples:

```
[2021-11-02, 09:47:10][ERROR][PDA/QRO/IJE] CommandInvokeError in command `xp`: Command raised an exception: ClientOSError: [Errno 32] Broken pipe
[2021-11-02, 09:47:10][ERROR][PDA/QRO/IJE] ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 85, in wrapped\n    ret = await coro(*args, **kwargs)\n', '  File "/var/www/discord-Writer-Bot/cogs/util/xp.py", line 45, in xp\n    await context.send(output)\n', '  File "/usr/local/lib/python3.8/dist-packages/discord/abc.py", line 904, in send\n    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,\n', '  File "/usr/local/lib/python3.8/dist-packages/discord/http.py", line 185, in request\n    async with self.__session.request(method, url, **kwargs) as r:\n', '  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 1012, in __aenter__\n    self._resp = await self._coro\n', '  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 504, in _request\n    await resp.start(conn)\n', '  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client_reqrep.py", line 847, in start\n    message, payload = await self._protocol.read()  # type: ignore  # noqa\n', '  File "/usr/local/lib/python3.8/dist-packages/aiohttp/streams.py", line 591, in read\n    await self._waiter\n', 'aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe\n', '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/bot.py", line 903, in invoke\n    await ctx.command.invoke(ctx)\n', '  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 859, in invoke\n    await injected(*ctx.args, **ctx.kwargs)\n', '  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 94, in wrapped\n    raise CommandInvokeError(exc) from exc\n', 'discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ClientOSError: [Errno 32] Broken pipe\n']
[2021-11-02, 09:47:10][ERROR][LRS/VHM/AJK] CommandInvokeError in command `sprint`: Command raised an exception: ClientOSError: [Errno 32] Broken pipe
[2021-11-02, 09:47:10][ERROR][LRS/VHM/AJK] ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 85, in wrapped\n    ret = await coro(*args, **kwargs)\n', '  File "/var/www/discord-Writer-Bot/cogs/writing/sprint.py", line 166, in sprint\n    return await self.run_join(context, opt1, opt2)\n', '  File "/var/www/discord-Writer-Bot/cogs/writing/sprint.py", line 502, in run_join\n    await context.send(user.get_mention() + \', \' + lib.get_string(\'sprint:join:update\', user.get_guild()).format(starting_wc))\n', '  File "/usr/local/lib/python3.8/dist-packages/discord/abc.py", line 904, in send\n    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,\n', '  File "/usr/local/lib/python3.8/dist-packages/discord/http.py", line 185, in request\n    async with self.__session.request(method, url, **kwargs) as r:\n', '  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 1012, in __aenter__\n    self._resp = await self._coro\n', '  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 504, in _request\n    await resp.start(conn)\n', '  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client_reqrep.py", line 847, in start\n    message, payload = await self._protocol.read()  # type: ignore  # noqa\n', '  File "/usr/local/lib/python3.8/dist-packages/aiohttp/streams.py", line 591, in read\n    await self._waiter\n', 'aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe\n', '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/bot.py", line 903, in invoke\n    await ctx.command.invoke(ctx)\n', '  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 859, in invoke\n    await injected(*ctx.args, **ctx.kwargs)\n', '  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 94, in wrapped\n    raise CommandInvokeError(exc) from exc\n', 'discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ClientOSError: [Errno 32] Broken pipe\n']

```

This was resulting in the generic error message with an error code, which wasn't helpful. It now specifically checks for this 'Broken pipe' error and displays text warning there are network issues. But it still needs to be resolved.

Server specs were increased, and CPU usage is now around 50% instead of high 90s, but it hasn't really helped.

Current lines of thinking:
- Is it some sort of rate limiting from discord? (Probably not, as it doesn't fit the expected behaviour if that was the case) [https://discord.com/developers/docs/topics/rate-limits#:~:text=All%20bots%20can%20make%20up,per%20second%20during%20normal%20operations]
- Is it some sort of timeout on the aiohttp request?

Very unsure at the moment.

**Comment by nim-rod-black** [comment]
Seeing similar issues on our discord. Subscribed!

**Comment by magneticflux-** [comment]
Some people have encountered similar issues with `aiohttp`:

- https://pulp.plan.io/issues/7186
- https://github.com/fsspec/gcsfs/issues/315
- https://stackoverflow.com/questions/71592527/broken-pipe-with-aiohttp
- https://github.com/HexCodeFFF/mediaforge/issues/80
- https://github.com/qtile/qtile/issues/2730
- https://github.com/related-sciences/ukb-gwas-pipeline-nealelab/issues/20
- https://github.com/aio-libs/aiohttp/issues/1799#issuecomment-416392390

I believe the root cause of the issue is that whatever webserver it is connecting to is closing the connection "ungracefully", which AIOHTTP is not happy about. Adding a retry feature for failed requests could help, you might be able to wrap the `ClientSession` used by `interactions.py` with [aiohttp-retry](https://pypi.org/project/aiohttp-retry/).

As for why it's closing connections... I have no idea. Maybe it's an issue with rate limiting? It might also be an issue with `Connection: keep-alive` headers. You could try adding `Connection: close` on the client end, but that would increase network load with HTTP renegotiation.
